#!/usr/bin/env bash
# Usage: ffs app command
# Summary: Manages application workflows
set -e

path=$0
SCRIPT_ROOT="${path%/*}"
source $SCRIPT_ROOT/shared-lib

# Provide ffs completions
if [ "$1" = "--complete" ]; then
  echo new
  echo remove
  echo bundle
  exit
fi

parse_options "$@"

# for option in "${OPTIONS[@]}"; do
  # echo "${option}"
# done

# for argument in "${ARGUMENTS[@]}"; do
  # echo "${argument}"
# done

create_app() {
  echo "Create new app: $1"
}

remove_app() {
  echo "Removing app: $1"
}

bundle_app() {
  if [ ! -e "${PWD}/Vagrantfile" ]
  then
    echo "No Vagrantfile found."
    echo "Must be in a directory with a Vagrantfile."
    exit 1
  fi

  required_status='running'
  current_status=$(vagrant status | grep -i '\(poweroff\|running\|not created\)')
  if [[ ! $current_status =~ "${required_status}" ]]
  then
    echo "Found Vagrantfile."
    echo "VM is not currently running."
    echo "Please 'vagrant up' and run 'ffs app bundle' again."
    exit 1
  fi

  vagrant ssh -c "cd /vagrant; bundle install --binstubs=bin --path vendor/bundle"
}

case "${ARGUMENTS[0]}" in
  "new" )
    APP_NAME="${ARGUMENTS[1]}"
    create_app "${APP_NAME}"
    exit 0
    ;;
  "remove" )
    APP_NAME="${ARGUMENTS[1]}"
    remove_app "${APP_NAME}"
    exit 0
    ;;
  "bundle" )
    APP_NAME="${ARGUMENTS[1]}"
    bundle_app "${APP_NAME}"
    exit 0
    ;;
esac

