#!/usr/bin/env bash
# Usage: ffs app command
# Summary: Manages application workflows
set -e

path=$0
SCRIPT_ROOT="${path%/*}"
source $SCRIPT_ROOT/shared-lib

# Provide ffs completions
if [ "$1" = "--complete" ]; then
  echo new
  echo remove
  echo bundle
  exit
fi

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

parse_options "$@"

create_app() {
  rvm gemset create $1
  rvm gemset use $1
  gem install rails
  rails new $1 --database=postgresql --skip-bundle
  cd $1
  echo "rvm 1.9.3-p286@${1} --create" > .rvmrc
  rvm rvmrc trust .
  git init
}

remove_app() {
  echo "Removing app: $1"
  rvm --force gemset delete $1
  rm -rf $1
}

bundle_app() {
  if [ ! -e "${PWD}/Vagrantfile" ]
  then
    echo "No Vagrantfile found."
    echo "Must be in a directory with a Vagrantfile."
    exit 1
  fi

  required_status='running'
  current_status=$(vagrant status | grep -i '\(poweroff\|running\|not created\)')
  if [[ ! $current_status =~ "${required_status}" ]]
  then
    echo "Found Vagrantfile."
    echo "VM is not currently running."
    echo "Please 'vagrant up' and run 'ffs app bundle' again."
    exit 1
  fi

  vagrant ssh -c "cd /vagrant; bundle install --binstubs --path vendor/bundle"
}

case "${ARGUMENTS[0]}" in
  "new" )
    APP_NAME="${ARGUMENTS[1]}"
    create_app "${APP_NAME}"
    exit 0
    ;;
  "remove" )
    APP_NAME="${ARGUMENTS[1]}"
    remove_app "${APP_NAME}"
    exit 0
    ;;
  "bundle" )
    APP_NAME="${ARGUMENTS[1]}"
    bundle_app "${APP_NAME}"
    exit 0
    ;;
esac

