#!/usr/bin/env bash
set -e

path=$0
SCRIPT_ROOT="${path%/*}"
source $SCRIPT_ROOT/shared-lib

if [ "$EUID" -ne "0" ]; then
  echo "This script must be run as root." >&2
  exit 1
fi

temp=`echo $1 | awk '{print tolower($0)}'`
install_dmg $1 $2 $temp
echo "${1} ${3} was successfully installed."

